routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//首页
Route::get('/', function () {
    return view('home.index');
});

Auth::routes();

//个人中心
Route::get('/home', 'HomeController@index')->name('home');

//常用信息
Route::prefix('info')->name('info.')->group(function () {
    Route::get('/', 'InfoController@index')->name('index');
    Route::get('buy', 'InfoController@buy')->name('buy');
    Route::get('mdl', 'InfoController@mdl')->name('mdl');
    Route::get('zb', 'InfoController@zb')->name('zb');
});

Route::middleware('auth')->group(function () {
//地址管理
    Route::prefix('address')->name('address.')->group(function () {
        Route::get('/', 'AddressController@index')->name('index');
        Route::post('store', 'AddressController@store')->name('store');
        Route::delete('destroy/{id}', 'AddressController@destroy')->name('destroy')->middleware('admin');
    });

//订单管理
    Route::prefix('order')->name('order.')->group(function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('create/{mall_id}', 'OrderController@create')->name('create');
        Route::post('store', 'OrderController@store')->name('store');
        Route::get('show/{id}', 'OrderController@show')->name('show');
        Route::post('success/{id}', 'OrderController@success')->name('success');
        Route::delete('destroy/{id}', 'OrderController@destroy')->name('destroy');
        Route::get('export_order/{id}', 'OrderController@export_order')->middleware('admin')->name('export_order');
    });
//购物车
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::get('/{mall_id}', 'CartController@index')->name('index');
        Route::post('store', 'CartController@store')->name('store');
        Route::delete('destroy/{id}', 'CartController@destroy')->name('destroy');
    });
    //建议留言
    Route::prefix('message')->name('message.')->group(function () {
        Route::get('/', 'MessageController@index')->name('index')->middleware('admin');
        Route::get('create', 'MessageController@create')->name('create');
        Route::post('store', 'MessageController@store')->name('store');
        Route::delete('destroy/{id}', 'MessageController@destroy')->name('destroy')->middleware('admin');
    });
});

//后台管理
Route::prefix('admin')->middleware('auth', 'admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('create/{mall_id}', 'AdminController@create')->name('create');
    Route::post('store', 'AdminController@store')->name('store');
    Route::get('edit/{mall_id}/{id}', 'AdminController@edit')->name('edit');
    Route::put('update/{id}', 'AdminController@update')->name('update');
    Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
    Route::post('pay', 'AdminController@pay')->name('pay');
    Route::post('pay_back', 'AdminController@pay_back')->name('pay_back');
    Route::get('product/{mall_id}', 'AdminController@product')->name('product');
    Route::get('order/{mall_id}', 'AdminController@order')->name('order');
    Route::post('trigger/{id}', 'AdminController@trigger')->name('trigger');
    Route::get('total_order/{mall_id}', 'AdminController@total_order')->name('total_order');
    Route::get('buytop', 'AdminController@buytop')->name('buytop');
    Route::match(['get','post'],'findpassword', 'AdminController@findpassword')->name('findpassword');

    //订单回收站
    Route::prefix('recycle')->name('recycle.')->group(function () {
        Route::get('/{mall_id}', 'OrderRecycleController@index')->name('index');
        Route::post('back_order', 'OrderRecycleController@back_order')->name('back_order');
        Route::delete('destroy', 'OrderRecycleController@destroy')->name('destroy');
    });

    //用户管理
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('edit/{id}', 'UserController@edit')->name('edit');
        Route::put('update/{id}', 'UserController@update')->name('update');
    });

    //用户记录管理
    Route::prefix('userlog')->name('userlog.')->group(function () {
        Route::get('/', 'UserLogController@index')->name('index');
    });

    //老年人管理
    Route::prefix('aged')->name('aged.')->group(function () {
        Route::get('/', 'AgedController@index')->name('index');
        Route::get('edit/{id}', 'AgedController@edit')->name('edit');
        Route::put('update/{id}', 'AgedController@update')->name('update');
        Route::get('create', 'AgedController@create')->name('create');
        Route::post('store', 'AgedController@store')->name('store');
        Route::delete('destroy/{id}', 'AgedController@destroy')->name('destroy');
    });

    //商户管理
    Route::prefix('mall')->name('mall.')->group(function () {
        Route::get('/', 'MallController@index')->name('index');
    });
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function mall()
    {
        return $this->belongsTo(Mall::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Mall;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if (Auth::check()) {
            $malls=Mall::all();
            return view('home',compact('malls'));
        } else {
            return view('home.index');
        }
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Aged;
use App\Cart;
use App\Mall;
use App\Order;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Exports\OrderExport;
use Maatwebsite\Excel\Facades\Excel;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::where('user_id', Auth::id())->paginate(10);
        foreach ($orders as $key => $value) {
            $products = json_decode($value->products);
            foreach ($products as $k => $val) {
                $orders[$key]['pro_text'] .= '['.$val->product->name.'×'.$val->total_num.']';
            }
        }
        return view('home.order.index', compact('orders'));
    }

    //选购界面
    public function create($mall_id)
    {
        $mall = Mall::find($mall_id);
        $address = Address::where('user_id', Auth::id())->first();
        if (is_null($address)) {
            return redirect(route('address.index'))->with('success', '请先添加姓名和电话再订菜');
        }

        //商品
        $products = Product::where('is_show', 1)->where('mall_id', $mall_id)->get();
        return view('home.order.create', compact('products', 'mall'));
    }

    //提交订单
    public function store(Request $request)
    {
        $mall_id = $request->input('mall_id');
        $is_show = Mall::find($mall_id)->is_show;
        //管理员不受系统开关限制
        if (!$is_show && Auth()->user()->is_admin != 1) {
            return back()->with('success', '系统已经关闭,订单提交失败!!!');
        }
        $carts = Cart::where('user_id', Auth::id())->where('mall_id', $mall_id)->get();
        if ($carts->count() == 0) {
            return back()->with('success', '购物车为空,订单提交失败!!!');
        }

        //购物车总金额
        try {
            $total_price = 0;
            foreach ($carts as $key => $value) {
                $total_price += $value->product->money * $value->total_num;
            }
        } catch (\Exception $exception) {
            return back()->with('success', '您的购物车中有失效的商品,请删除后重新提交订单!!!');
        }

        //是否为代买模式 只允许管理员代买
        $aged_id = $request->input('aged_id');
        if ($aged_id != 0 && Auth::user()->is_admin == 1) {
            $address = Aged::find($aged_id);
            $data['name'] = $address->name;
            $data['tel'] = $address->tel;
        } else {
            $address = Address::where('user_id', Auth::id())->first();
            $data['name'] = $address->name;
            $data['tel'] = $address->tel;
        }

        $data['user_id'] = Auth::id();
        $data['products'] = json_encode($carts->toArray());
        $data['total_money'] = $total_price;
        $data['total_num'] = array_sum($carts->pluck('total_num')->toArray());
        $data['mall_id'] = $mall_id;
        try {
            $order = DB::transaction(function () use ($data, $mall_id, $carts) {
                //创建订单
                $order = Order::create($data);
                //减商品对应的库存
                foreach ($carts as $cart) {
                    $product = Product::lockForUpdate()->find($cart->product_id);
                    $product->decrement('stock', $cart->total_num);
                    //如果库存为负数则抛出异常
                    if ($product->stock < 0) {
                        throw new \Exception('当前商品'.$product->name.'库存不足，提交订单失败!');
                    }
                }
                //清空购物车
                Cart::where('user_id', Auth::id())->where('mall_id', $mall_id)->delete();
                return $order;
            }, 5);
        } catch (\Exception $exception) {
            return back()->with('success', '提交订单失败!!!!!'.$exception->getMessage());
        }
        return redirect(route('order.show', $order->id))->with('pay_success', '提交订单成功');
    }

    //显示订单
    public function show($id)
    {
        $order = Order::with('mall')->where('user_id', Auth::id())->where('id', $id)->first();
        $products = json_decode($order->products);
        $pro_text = null;
        foreach ($products as $key => $value) {
            $pro_text .= '['.$value->product->name.'×'.$value->total_num.']';
        }
        return view('home.order.show', compact('order', 'pro_text'));
    }

    //确认收货
    public function success(Request $request, $id)
    {
        $order = Order::where('user_id', Auth::id())->where('id', $id)->first();
        if (is_null($order->pay_time)) {
            return back()->with('success', '确认收货失败！此订单未付款。如果您已经付款，请联系商家确认收款！');
        }
        $update = $order->update(['is_success' => 1]);
        if ($update) {
            return back()->with('success', '确认收货成功!');
        } else {
            return back()->with('success', '确认收货失败!!!!!');
        }
    }

    //删除订单
    public function destroy(Request $request, $id)
    {
        //判断是否从后台发起删除请求
        $is_admin = $request->input('is_admin');
        $order = Order::find($id);
        if (is_null($order)) {
            return back()->with('success', '订单不存在,可能已经被删除了!!!!');
        }
        //订单未支付并且未收货
        if (is_null($order->pay_time) && $order->is_success === 0) {
            $del = DB::transaction(function () use ($id, $order) {
                $products = json_decode($order->products, true);
                foreach ($products as $product) {
                    $this_product = Product::find($product['product']['id']);
                    //商品存在并且是当天删除的情况下还库存
                    if (!is_null($this_product) &&  (date("Y-m-d",strtotime($order->created_at))==date("Y-m-d")) ) {
                        $this_product->increment('stock', $product['total_num']);
                    }
                }
                //删除订单
                return Order::destroy($id);
            });

            //删除成功
            if ($del) {
                if ($is_admin) {
                    return back()->with('success', '订单删除成功!');
                }
                return redirect(route('order.index'))->with('success', '订单删除成功!');
            }

            //删除失败
            if (!$del) {
                return back()->with('success', '订单删除失败!!!!!');
            }

        } else {
            return back()->with('success', '订单已经支付或者已经收货，无法删除！！！');
        }
    }

    //导出订单
    public function export_order(Request $request, $id)
    {
        $mall_id = $id;
        $s_id = array();
        if ($request->input('s_id') != '') {
            $s_id = function ($query) use ($request) {
                $query->where('id', $request->input('s_id'));
            };
        }

        //按收货人姓名搜索
        $s_name = array();
        if ($request->input('s_name') != '') {
            $s_name = function ($query) use ($request) {
                $query->where('name', $request->input('s_name'));
            };
        }
        //按收货人电话搜索
        $s_tel = array();
        if ($request->input('s_tel') != '') {
            $s_tel = function ($query) use ($request) {
                $query->where('tel', $request->input('s_tel'));
            };
        }

        $c_time = array();
        if ($request->input('created_at') != '') {
            $c_date = str_replace(' ', '', $request->input('created_at'));
            $start_c_date = explode('~', $c_date)[0];
            $end_c_date = explode('~', $c_date)[1];
            $c_time = function ($query) use ($start_c_date, $end_c_date) {
                $query->whereDate('created_at', '>=', $start_c_date)->whereDate('created_at', '<=', $end_c_date);
            };
        }
        $p_time = array();
        if ($request->input('pay_date') != '') {
            $p_date = str_replace(' ', '', $request->input('pay_date'));
            $start_p_date = explode('~', $p_date)[0];
            $end_p_date = explode('~', $p_date)[1];
            $p_time = function ($query) use ($start_p_date, $end_p_date) {
                $query->whereDate('pay_time', '>=', $start_p_date)->whereDate('pay_time', '<=', $end_p_date);
            };
        }
        $p_state = array();
        if ($request->input('pay_state') == 'y') {
            $p_state = function ($query) use ($request) {
                $query->whereNotNull('pay_time');
            };
        }
        if ($request->input('pay_state') == 'n') {
            $p_state = function ($query) use ($request) {
                $query->whereNull('pay_time');
            };
        }
        $success = array();
        if ($request->input('is_success') == 'y') {
            $success = function ($query) use ($request) {
                $query->where('is_success', '=', 1);
            };
        }
        if ($request->input('is_success') == 'n') {
            $success = function ($query) use ($request) {
                $query->where('is_success', '=', 0);
            };
        }
        $orders = Order::with('mall')->where('mall_id', $mall_id)
            ->where($c_time)
            ->where($p_time)
            ->where($p_state)
            ->where($success)
            ->where($s_id)
            ->where($s_name)
            ->where($s_tel)
            ->get();

        foreach ($orders as $key => $value) {
            $pros = json_decode($value->products);
            foreach ($pros as $k => $val) {
                $orders[$key]['pro_text'] .= '['.$val->product->name.'×'.$val->total_num.']';
                $orders[$key]['mall_name'] = $value->mall->name;
            }
            unset ($value['mall'], $value['products'], $value['user_id'], $value['deleted_at'], $value['updated_at'], $value['mall_id']);
        }
        return Excel::download(new OrderExport($orders->toArray()), 'order_'.time().'.xlsx');
    }
}

resources/views/home/order/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        @if($mall->is_show==0)
            <div class="alert alert-danger" role="alert">
                {{ $mall->name }}当前休息中，你可以逛逛其他商家。
            </div>
        @endif
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">个人中心</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ $mall->name }}</li>
                <li class="breadcrumb-item"><a href="{{ route('cart.index',$mall->id) }}">我的购物车</a></li>
            </ol>
        </nav>
        <div class="row">
            @foreach($products as $product)
                <div class="col-md-4">
                    <div class="card" style="width: 20rem; margin: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ $product->name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">￥{{ $product->money }}
                                剩余库存：{{ $product->stock }}</h6>
                            <div class="form-group">
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="10"
                                          disabled>{{ $product->description }}</textarea>
                            </div>
                            <form action="{{route('cart.store')}}" method="post">
                                @csrf
                                <input type="hidden" name="product_id" value="{{ $product->id }}">
                                <input type="hidden" name="mall_id" value="{{ $mall->id }}">
                                <input type="hidden" name="num" value="1">
                                @if($mall->is_show==0)
                                    <button type="submit" class="btn btn-warning" onclick="alert('点击继续……')" disabled>
                                        商家休息中...
                                    </button>
                                    @if(Auth()->user()->is_admin==1)
                                        <button type="submit" class="btn btn-danger" onclick="alert('点击继续……')">√
                                        </button>
                                    @endif
                                @endif
                                @if($mall->is_show==1)
                                    @if($product->stock <= 0)
                                        <button type="submit" class="btn btn-secondary" onclick="alert('点击继续……')"
                                                disabled>卖完了...
                                        </button>
                                    @else
                                        <button type="submit" class="btn btn-danger" onclick="alert('点击继续……')">加入购物车
                                        </button>
                                    @endif
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>


@endsection

resources/views/home/order/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">个人中心</a></li>
                <li class="breadcrumb-item active" aria-current="page">我的订单</li>
            </ol>
        </nav>
        <div class="row ">
            @foreach($orders as $order)
                <div class="col-md-4">
                    <div class="card" style="width: 92%; margin: 10px;">
                        <div class="card-header">
                            订单号:{{ $order['id'] }} 收货人:{{ $order['name'] }} {{ $order['tel'] }}
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-4">{{  $order['pro_text'] }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">共{{ $order['total_num'] }}件
                                ￥{{ $order['total_money'] }}</h6>
                            <h6 class="card-subtitle mb-2 text-muted">下单时间 {{ $order['created_at'] }}</h6>
                            <span class="badge badge-danger"
                                  style="margin-right: 5px;font-size: 85%!important;">商家：{{ $order['mall']->name }}</span>
                            @if(is_null($order['pay_time']))
                                <span class="badge badge-warning" style="font-size: 85%!important;">未付款</span>
                            @else
                                <span class="badge badge-success" style="font-size: 85%!important;">已付款</span>
                            @endif
                        </div>
                        <div class="card-footer bg-transparent ">
                            @if($order['is_success']===0)
                                @if(is_null($order['pay_time']))
                                    <button type="button" class="btn btn-danger btn-sm"
                                            style="float:left;margin-right: 10px;" data-toggle="modal"
                                            data-target="#order_pay_{{ $order->id }}">立即付款
                                    </button>
                                @else
                                    <form action="{{ route('order.success',$order['id']) }}" method="post"
                                          style="float:left;margin-right:10px;">
                                        @csrf
                                        <input type="hidden" name="order_id" value="{{ $order['id'] }}">
                                        <button type="submit" class="btn btn-primary btn-sm">确认收货</button>
                                    </form>
                                @endif
                                @if(is_null($order['pay_time']))
                                    <form action="{{ route('order.destroy',$order['id']) }}" method="post"
                                          style="float:left;margin-right: 10px;">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-dark btn-sm">删除订单</button>
                                    </form>
                                @endif
                            @else
                                <button type="button" class="btn btn-success btn-sm" disabled style="cursor: default;">
                                    已经收货
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <hr>
        {{ $orders->links() }}
    </div>
    @foreach($orders as $order)
        <div class="modal fade" id="order_pay_{{ $order->id }}" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="order_success" aria-hidden="true">
            <div class="modal-dialog modal-sm " role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">付款方式</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <img src="{{$order->mall->pay_qrcode}}" class="card-img-top img-responsive center-block">
                            <div class="card-body">
                                <h6 class="card-title">加好友付款需知</h6>
                                <p class="card-text">订单号+姓名+电话+金额 然后转账</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection

resources/views/home/order/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">首页</a></li>
                <li class="breadcrumb-item"><a href="{{ route('order.index') }}">我的订单</a></li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        订单号:{{ $order->id }} 收货人:{{ $order->name }} {{ $order->tel }}
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-4">{{  $pro_text }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">商家:{{ $order->mall->name }}
                            共{{ $order['total_num'] }}件 ￥{{ $order['total_money'] }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">下单时间 {{ $order['created_at'] }}</h6>
                        @if(is_null($order['pay_time']))
                            <span class="badge badge-warning">未付款</span>
                        @else
                            <span class="badge badge-success">已付款</span>
                        @endif
                    </div>
                    <div class="card-footer bg-transparent ">
                        <button type="button" class="btn btn-danger btn-sm"
                                style="float:left;margin-right: 10px;" data-toggle="modal"
                                data-target="#order_pay_show">立即付款
                        </button>
                        <form action="{{ route('order.success',$order['id']) }}" method="post" style="float:left;">
                            @csrf
                            <input type="hidden" name="order_id" value="{{ $order['id'] }}">
                            @if($order['is_success']===0)
                                <button type="submit" class="btn btn-primary btn-sm">确认收货</button>
                            @else
                                <button type="button" class="btn btn-success btn-sm">已经收货</button>
                            @endif
                        </form>
                        <form action="{{ route('order.destroy',$order['id']) }}" method="post"
                              style="float:left;margin-left:10px;">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-dark btn-sm">删除订单</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            <hr>
            <a href="{{ route('order.index') }}"> <button class="btn btn-danger btn-sm">查看所有订单</button></a>

    </div>

    @if (session('pay_success'))
        <div class="modal fade" id="order_success" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="order_success" aria-hidden="true">
            <div class="modal-dialog modal-sm " role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel"> {{ session('pay_success') }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card">
                            <img src="{{$order->mall->pay_qrcode}}" class="card-img-top img-responsive center-block">
                            <div class="card-body">
                                <h6 class="card-title">加好友付款需知</h6>
                                <p class="card-text">订单号+姓名+电话+金额 然后转账</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
                    </div>
                </div>
            </div>
        </div>
    @endif
    <div class="modal fade" id="order_pay_show" data-backdrop="static" tabindex="-1" role="dialog"
         aria-labelledby="order_success" aria-hidden="true">
        <div class="modal-dialog modal-sm " role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">付款方式</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="card">
                        <img src="{{$order->mall->pay_qrcode}}" class="card-img-top img-responsive center-block">
                        <div class="card-body">
                            <h6 class="card-title">加好友付款需知</h6>
                            <p class="card-text">订单号+姓名+电话+金额 然后转账</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(function () {
            $("#order_success").modal('show');
        })
    </script>
@endsection